[PayPal]
	Enabled = true

	; The URL to reference PayPal by
	; can be either www.paypal.com or www.sandbox.paypal.com
	PayPalURL = www.paypal.com

	; Fetch email addresses from the User grid service; default is false
	AllowGridEmails = false

	; Allow group PayPal accounts; default is false
	AllowGroups = false

[PayPal Users]
; Addresses of Receivers/Sellers PP user accounts
; One per line, ie:
;Plaza Builder=donations.osgrid@gmail.com
; ...

[PayPal Groups]
; Addresses of Receivers/Sellers PP group accounts, keyed by group UUID
; One per line, ie:
;a683cc8a-a5cc-4c40-87bc-ebcfbcfb1456=mygroup.account@yahoo.com
; ...
